apiVersion: v2
name: freedom-sentry-helm
version: 0.2.0
appVersion: "1.1.0"
description: MediaWiki bot for Wikipedia to suppress edit metadata for sensitive articles
type: application
keywords:
  - mediawiki
  - wikipedia
  - privacy
maintainers:
  - name: wizardist
