{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freedom-sentry.fullname" . }}
  labels:
    {{- include "freedom-sentry.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessToken: {{ .Values.secret.accessToken | quote }}
{{- end }}
